### ISSUE TITLE
Bug with Scheduler API with newer versions of Werkzeug

### ISSUE THREAD

**Issue by zexpe** [viniciuschiele/flask-apscheduler#203]
Calling the "/scheduler/jobs" route works with Werkzeug 0.14.1, but on a newer system upgraded to 2.0.1, I get the following error:

Internal Server Error: AttributeError: 'Request' object has no attribute 'is_xhr'

This line is to blame:

  File "~/.local/lib/python3.9/site-packages/flask_apscheduler/json.py", line 21, in jsonify
    if flask.current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not flask.request.is_xhr:

Apparently is_xhr is deprecated in newer versions of Werkzeug.

**Comment by viniciuschiele** [comment]
Thanks for reporting that, I will release a fix
