### ISSUE TITLE
AttributeError: 'module' object has no attribute 'loads'

### ISSUE THREAD

**Issue by alexonab** [viniciuschiele/flask-apscheduler#9]
I have loaded the latest build and am unable to get the advanced.py example to run.  Any idea what I may be missing?

```
$ python foo.py    
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    from flask_apscheduler import APScheduler
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/__init__.py", line 17, in <module>
    from flask_apscheduler.scheduler import APScheduler
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 22, in <module>
    from . import views
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/views.py", line 18, in <module>
    from .json import jsonify
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/json.py", line 8, in <module>
    loads = json.loads
AttributeError: 'module' object has no attribute 'loads'
```

**Comment by viniciuschiele** [comment]
There is an issue in the latest build with Python 2.7, I will sort it out.

**Comment by viniciuschiele** [comment]
I just released the version 1.3.5 that fixes this issue.

Thanks for reporting it.
